//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommentManagerEntities : DbContext
    {
        public CommentManagerEntities()
            : base("name=CommentManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acceptance_status> Acceptance_status { get; set; }
        public virtual DbSet<Cause> Cause { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Drawing> Drawing { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Expertise> Expertise { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Group_Expertise> Group_Expertise { get; set; }
        public virtual DbSet<Kit_status> Kit_status { get; set; }
        public virtual DbSet<Organizations> Organizations { get; set; }
        public virtual DbSet<Project_Info> Project_Info { get; set; }
        public virtual DbSet<Project_Status> Project_Status { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Remark> Remark { get; set; }
        public virtual DbSet<Response_Project_Company_> Response_Project_Company_ { get; set; }
        public virtual DbSet<Response_status> Response_status { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Set_remarks> Set_remarks { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<Type_complex__object> Type_complex__object { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
