//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project_Info()
        {
            this.Projects = new HashSet<Projects>();
        }
    
        public int ID { get; set; }
        public int Drawing_ID { get; set; }
        public string Object_name { get; set; }
        public int Type_complex__object_ID { get; set; }
        public int Expertise_ID { get; set; }
        public int Group_Expertise_ID { get; set; }
    
        public virtual Drawing Drawing { get; set; }
        public virtual Expertise Expertise { get; set; }
        public virtual Group_Expertise Group_Expertise { get; set; }
        public virtual Type_complex__object Type_complex__object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
