//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.Remark = new HashSet<Remark>();
            this.Task = new HashSet<Task>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int Contract_number { get; set; }
        public int Year { get; set; }
        public int Project_manager { get; set; }
        public Nullable<int> Project_info_ID { get; set; }
        public int Status_ID { get; set; }
        public int Customer_ID { get; set; }
        public int General_designer_ID { get; set; }
        public int Сreator_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Organizations Organizations1 { get; set; }
        public virtual Organizations Organizations2 { get; set; }
        public virtual Project_Info Project_Info { get; set; }
        public virtual Project_Status Project_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remark> Remark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Task { get; set; }
    }
}
