//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Time { get; set; }
        public string Attachment { get; set; }
        public int Cause_code_ID { get; set; }
        public int Performer_ID { get; set; }
        public int Response_project_company_ID { get; set; }
        public int Project_info_ID { get; set; }
        public int Acceptance_status_ID { get; set; }
        public int Customer_ID { get; set; }
        public Nullable<System.DateTime> Date_completion { get; set; }
        public string Text { get; set; }
        public string Link_On_Documentation { get; set; }
        public System.DateTime Date_Create { get; set; }
    
        public virtual Acceptance_status Acceptance_status { get; set; }
        public virtual Cause Cause { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Organizations Organizations1 { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual Response_Project_Company_ Response_Project_Company_ { get; set; }
    }
}
